export const Categories = [
    {
        'id': 1,
        'img':"https://img.narong.dev/onguaJ8Iz7u18mMzspVNp7nIl-7v8w84My9twhsMalI/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvYWNjZXNzb3JpZXNfMjA4OTQ5ZTM4MmI2NTcwOGE5ODBjMzVmYTAzYWU0MTgucG5n.webp",
        'name':'Accessory',
        'type':'accessory'
    },
    {
        'id':2,
        'img':"https://img.narong.dev/6lmO8Adrku5gDRA7e3txyERjWmZmqjwOKjEDDLciWn4/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLzJfZDg3MjdkY2VjMy5wbmc.webp",
        'name':'CPU',
        'type':'cpu'
    },
    {
        'id':3,
        'img':"https://img.narong.dev/9YYn8lF4lmfdOhwguHr51LAUzOhKTDTVuWdkChrKGTU/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvY29tYm9fMjMxNjFiMGM4NWZhNzIwZTJmMmMwMTc3MjM4Y2Q0ZDYucG5n.webp",
        'name':'Combo',
        'type':'combo'
    },
    {
        'id':4,
        'img':"https://img.narong.dev/qMRTKD9eIWB95I9iCsneNbCGPnczeF665Sq7PnC4RyM/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvY29udHJvbGxlcl84ZGNiZjRkMDY1MTRkZGE0MTk5ZTllMjA3OWNlMTU5Ni5wbmc.webp",
        'name':'Controller',
        'type':'controller'
    },
    {
        'id':5,
        'img':"https://img.narong.dev/fLXjVisHW-TvzW3Y47stKF25vSUjVjDq8lS-suREF9I/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL0NQVV9jb29sZXJfMmYyYTMxZjViMDJjOWE1OTkzOWQ4OGU0ZDg5NWI5YTEucG5n.webp",
        'name':'cooler',
        'type':'cooler'
    },
    {
        'id':6,
        'img':"https://img.narong.dev/PTWITNCjZc0kjmPP-YWbtz6n1VodODcoeq08VSTopKw/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvY29vbGluZ19wYWRfYTY3ZTAxZjY3NDJhZjg4YzcyNzM2MWYwYTA1MmJlMjcucG5n.webp",
        'name':'cooling pad',
        'type':'coolingpad'
    },
    {
        'id':7,
        'img':"https://img.narong.dev/kvKqs5kJYg8fRWirm0DZSJXIYDXQGBySZ8Bk4XlLCac/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL0N1c3RvbV9CdWlsdF8xZjlhMWYyMWNhYTYyMzI0M2JhZTQyNzEwNjIwZGExMi5wbmc.webp",
        'name':'Custom PC',
        'type':'custompc'
    },
    {
        'id':8,
        'img':"https://img.narong.dev/VvBw-7G_D-hlNdKlbLn0TKuIQL3bBTdINdKrnrIVVnc/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvZGl5X2VjYzZlY2NkOGM4YzcyYjg5MTBlMTU2YTAyODIwNjVmLnBuZw.webp",
        'name':'DIY',
        'type':'diy'
    },
    {
        'id':9,
        'img':"https://img.narong.dev/MCQ52AYFeRn5r5KSH5ORHlTkra1sq7IXIAG7_KIZG90/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2Zhbl9jZDY2NzgyN2E3YzBlNDIxZDcwY2RlNzQyYzc3ZjIzNi5wbmc.webp",
        'name':'Fan',
        'type':'fan'
    },
    {
        'id':10,
        'img':"https://img.narong.dev/i5v-1iKPZJnLadkukLccQHN7LBA793OtYTQRjsbEYIM/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3ZnYV8yYmM2NjAwOWFlYTUwZWRiNjY0OTM5ODE3NGRmNDdiMS5wbmc.webp",
        'name':'Graphic card (VGA)',
        'type':'graphiccardVGA)'
    },
    {
        'id':11,
        'img':"https://img.narong.dev/bpgFQUbXup8L3rhQDr7l9BNS-ftzr-gxhAoFH7ODNWk/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvaGVhZHBob25lX2FjZjRiMzdkNzIxOTcyZDcyYmIyYTIzZTg0ODVkNzliLnBuZw.webp",
        'name':'Headphone',
        'type':'headphone'
    },
    {
        'id':12,
        'img':"https://img.narong.dev/MApVN8FmU4zbcFGzaSoR3sE7h2SqATJItma1HDcAZvA/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUva2V5Ym9hcmRfOTM1OTVhZDdmODAzMTRlMTMxNDkwNTZkYjU5NDgyYjkucG5n.webp",
        'name':'Keyboard',
        'type':'keyboard'
    },
    {
        'id':13,
        'img':"https://img.narong.dev/W3R_tMOkhabeXhlsykj8bN06bPKjnN0HSc_OR1lxwxs/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUva2V5Y2Fwc19mZTE5ODZmZDY5MGY2OTM3YjZiOTg2NDI3ODc5ZjQzYy5wbmc.webp",
        'name':'Keycaps',
        'type':'keycaps'
    },
    {
        'id':14,
        'img':"https://img.narong.dev/uTJz6o11p6BzIytBES2_OQiftmX66iiJxxifq0TMsRo/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvbGlnaHRzdHJpcF85MWY3NTY2ZGQ0YTZiNzkwMjBiN2E5YzA0ZDQ2ZDQ0OC5wbmc.webp",
        'name':'Light Strip',
        'type':'lightstrip'
    },
    {
        'id':15,
        'img':"https://img.narong.dev/A0qTFHbGneG2U_xqc6ID0jnvVOptmX8RZUUzz47uvUA/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvbWljcm9waG9uZV83Y2NhZGUzZWFjNWJjMTE4ZDBjMDJmNDlkNDM2NzZmOS5wbmc.webp",
        'name':'Microphone',
        'type':'microphone'
    },
    {
        'id':16,
        'img':"https://img.narong.dev/zChFSSgQLAo4QebRbSXCV8T16z_EDqjqdLQrbk2lptc/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL21vbml0b3JfMWViNDU5ZjA1YTViNDhkNmM3NDFiMGEyODg5MmI4NjQucG5n.webp",
        'name':'Monitor',
        'type':'monitor'
    },
    {
        'id':17,
        'img':"https://img.narong.dev/B1Dk6rkcqiM1ZUPsiKOnOoEcz7dJf190z1tX45mTYyw/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL21vdGhlcmJvYXJkXzRjNjZhY2UwOGY2ZTk0NDM4MGE4OTlkYmIwMTIyMTI1LnBuZw.webp",
        'name':'Motherboard',
        'type':'motherboard'
    },
    {
        'id':18,
        'img':"https://img.narong.dev/_ao2KKCAjBCPFjOXHhkp-KQNnwseDMlmYVSqsBxBAgU/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvbW91c2VfMDYwNWY0ZWI4Zjk3YzIwODEwNjk5ODdmMmU2MDFkNDgucG5n.webp",
        'name':'Mouse',
        'type':'mouse'
    },
    {
        'id':19,
        'img':"https://img.narong.dev/a-6sh1uHRskRQ26G9SIcCsmxG86wsOMZKhKromRu2fw/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvbW91c2VwYWRfZGI2MWY0MGY2ZThmNzk0NTFlMjhjZmI3ZDQ5YTdjNGQucG5n.webp",
        'name':'Mousepad',
        'type':'mousepad'
    },
    {
        'id':20,
        'img':"https://img.narong.dev/BCxQ0EglNCjI_7ODhowp8ePhztA5KPwu2FT-UJ8WTmc/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2Nhc2VfYTkyZjdiZWM3YzRlMTc3N2YxNTI0NWI0MDI5ZDcyYWMucG5n.webp",
        'name':'PC Case',
        'type':'pccase'
    },
    {
        'id':21,
        'img':"https://img.narong.dev/0eWKdX_h592PJZdbT7u0B4u5_pr-eb_opUTg9T-1BUs/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3Bvd2VyX3N1cHBseV83OGM5ZTgyZWJmNmIzYzkxNDVmN2IxMTFiZmNhZDM1Mi5wbmc.webp",
        'name':'Power Supply Unit',
        'type':'powersupplyunit'
    },
    {
        'id':22,
        'img':"https://img.narong.dev/00mCn3n7BMlfDq6DOdraJQ5upt3qIQr2zIsGJjwHSB0/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3JhbV9lZmVmNTdkMGI0MDAwMGI0MmQyMDA1ZWU5NmIwNWQ3ZS5wbmc.webp",
        'name':'RAM',
        'type':'ram'
    },
    {
        'id':23,
        'img':"https://img.narong.dev/rW_v1pFOJd5-zPPM7z75x74G3IE3q2wJzBaA5scNih8/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvc3BlYWtlcl8wYmQ2NmEzMDU2YmMwMTVlODNjNTRkZjEwODMyMTBjNi5wbmc.webp",
        'name':'Speaker',
        'type':'speaker'
    },
    {
        'id':24,
        'img':"https://img.narong.dev/LbWRB1ooaRb5yshfIpZXMTZ5ZohlrYi6DNjR9s7Gm5k/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3N0b3JhZ2VfNjMxZGY3OWI2ZWE3NTIxY2U1NjVkZWM0YTVkZmYyN2IucG5n.webp",
        'name':'Storage',
        'type':'storage'
    },
    {
        'id':25,
        'img':"https://img.narong.dev/X9geokHxO1Sj-fhJ3o11ssEzs0RfYqChxhjTcjS-s6A/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvc3dpdGNoXzQwNWY3MWIyYzk3NTEwMDM5YzIyYTkwZmJhN2RlYjgyLnBuZw.webp",
        'name':'Switch',
        'type':'switch'
    },
    {
        'id':26,
        'img':"https://img.narong.dev/viX6aHu1DAL_7gM5Wq7Dyq2WhUIl4Fl4VdWUJSgwInw/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvY2hhaXJfYW5kX3RhYmxlXzRhM2MwYWRjODE2YjFlNDM3MGMzZTgwOWU2ZmExNGVmLnBuZw.webp",
        'name':'Table / Chair',
        'type':'tablechair'
    },
    {
        'id':27,
        'img':"https://img.narong.dev/4J9JDtEguux7AfmegZdb58v0ANCoYgg6co3ExcYb26c/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGUvd2ViY2FtX2Y1YTQ5YWU3NjYxMWMzZDYwOTJlZDM0NGUxYjQzMjZkLnBuZw.webp",
        'name':'Webcam',
        'type':'webcam'
    }
] 