export const Devices = [
    {
          'id': 1,
           'img': 'https://img.narong.dev/2RelIwWDVAjr2nYZML5snc73U6L96flqEZa6Ty3IAao/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3JhemVyX2xldmlhdGhhbl92Ml83ZjdkNTE5OTIwYmY2Y2VkOGIwMjBlMTk0MThiNzFlYS5qcGc.webp',
           'name':'Leviathan V2 ',
           'brand':'Razer',
           'price': 239,
    },
    {
        'id': 2,
        'img': 'https://img.narong.dev/HoVF-u2-mGaqCn2vwu19zQrHl7rovtVBI8BAhDGcvMw/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2xvZ2l0ZWNoX19fbXhfa2V5c19taW5pX2NvbWJvX2Y1YzQ1NTU5MmViZTgzNTc0ZDc2YWM5YTE1NzU1ZTRkLnBuZw.webp',
        'name': 'MX Keys Mini Combo for business',
        'brand': 'Logitech',
        'price': 179,
    },
    {
        'id': 3,
        'img': 'https://img.narong.dev/LLNdt4-gha1F8YcpvzSp16IevfrWhPuNLraAZqGJ6Tc/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2xvZ2l0ZWNoX19fbXhfa2V5c19fX2NvbWJvXzg5MDZhMDdiYTcxYzI2MjY1Y2YxNDkwN2JkM2I2MjYxLnBuZw.webp',
        'name': 'MX Keys S Combo for business',
        'brand': 'Logitech',
        'oldPrice': 219,
        'price': 199,
    },
    {
        'id': 4,
        'img': 'https://img.narong.dev/V2MTyTnUDbeOnXi4TN85YgO8L5t19qV-ugROPm3pbVk/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3JhemVyX19fYmFycmFjdWRhX3Byb18xZjRlOGVkMGQxYTdkN2NjNDgxMjlkOTU1ZmExYzg0ZC5wbmc.webp',
        'name': 'Barracuda Pro',
        'brand': 'Razer',
        'price': 259,
    },
    {
        'id': 5,
        'img': 'https://img.narong.dev/YFt-EZPwrM0xY_HMc0PvMW--Ho5kQhoUcngEpe-7SOI/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL3JhemVyX19fZGVhdGhhZGRlcl92M19fX2JsYWNrXzRlMjk1MWMyNTg3NDk0NTcwNDllOWYzMTZlMDAxYTBkLnBuZw.webp',
        'name': 'DeathAdder V3',
        'brand': 'Razer',
        'price': 79,
    },
]

export const ProductMouses  = [
    {
        'id':1,
        'img':'https://img.narong.dev/uaJCfKGk9BHBJ_GMPjH-BSgAZalx7AnltLka6j4_h3Q/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fd2lyZWxlc3Nfd2hpdGVfMWFlYWM1MTM3MC5wbmc.webp',
        'name': 'Model O Wireless',
        'brand': 'Glorious',
        'oldPrice': 105,
        'price': 95,
    },
    {
        'id':2,
        'img':'https://img.narong.dev/vfelH4JAnzjCIF5ZiZE7gMYx_DLQUjW6L8-kSPqfYoY/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fd2lyZWxlc3NfYmxhY2tfMzI3YzdmZjA1OS5wbmc.webp',
        'name': 'Model O Wireless',
        'brand': 'Glorious',
        'oldPrice': 105,
        'price': 95,
    },
    {
        'id':3,
        'img':'https://img.narong.dev/cKOYfJmOBqKxEWI4LnrZRobj0hHwC-Mp9K2KtWHh-Aw/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fd2hpdGVfZGFiYjZlYzA0OC5wbmc.webp',
        'name': 'Model O',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59 ,
    },
    {
        'id':4,
        'img':'https://img.narong.dev/KrMPA15i7JtgsYNLhWMKxqGp448_2MNmi7TNKPcl7YY/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fYmxhY2tfYjdhZTY1OTgxYy5wbmc.webp',
        'name': 'Model O',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59,
    },
    {
        'id':5,
        'img':'https://img.narong.dev/gY-io-qhN9cJ0_ZBix9-Y3OmVVuF-YPwMuf1SV4U7q4/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fd2hpdGVfNGQyNGExMDQwYi5wbmc.webp',
        'name': 'Model O Minus',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59,
    },
    {
        'id':6,
        'img':'https://img.narong.dev/6ExuVTfl56Qgu2-sCenkhuzZb4QvE2bgyyfwdHMcIm0/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fYmxhY2tfNGY3NzQxYmMxYy5wbmc.webp',
        'name': 'Model O Minus',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59,
    },
    {
        'id':7,
        'img':'https://img.narong.dev/O0AOhp44mi5aqst9IOlEoxFPdvWlW1kOi_ZUP9eUmSo/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fd2lyZWxlc3NfYmxhY2tfZjhlYmQ1ZjIzZS5wbmc.webp',
        'name': 'Model O Minus Wireless',
        'brand': 'Glorious',
        'oldPrice': 105,
        'price': 95 ,
    },
    {
        'id':8,
        'img':'https://img.narong.dev/mZsiOw-WMKT382uytI1tjWMgLXNAkcOR7KcApY9p4y4/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL29fd2lyZWxlc3Nfd2hpdGVfNDQ0OTBhODBmYy5wbmc.webp',
        'name': 'Model O Minus Wireless',
        'brand': 'Glorious',
        'oldPrice': 105,
        'price': 95,
    },
    {
        'id':9,
        'img':'https://img.narong.dev/muGni9ILxztdlCfbP-H_FwMIs8wgfZFQvtPCz0Ayqxs/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL2RfYmxhY2tfYmQ0NmI5ZjNkNS5wbmc.webp',
        'name': 'Model D',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59,
    },
    {
        'id':10,
        'img':'https://img.narong.dev/FkSz7aoNmxbHEX5KpwyBvL8Lv_lEcSzHnoslRP_NyCA/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL2Rfd2hpdGVfY2ZlMTJlNDNhNi5wbmc.webp',
        'name': 'Model D',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59,
    },
    {
        'id':11,
        'img':'https://img.narong.dev/KSf36QrEEeUB8009lOMrUtrWKxMgjRvn8qnCKsmeoaI/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL2Rfd2lyZWxlc3NfYmxhY2tfZWI2Y2VmOGFkOS5wbmc.webp',
        'name': 'Model D Wireless',
        'brand': 'Glorious',
        'oldPrice': 105,
        'price': 95,
    },
    {
        'id':12,
        'img':'https://img.narong.dev/yRK_O-Kw8cO7Jqw_K5ng1eTH6sG9LQQEC2DUxRqU0VE/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL2Rfd2hpdGVfNDc1NWRhMWU3NS5wbmc.webp',
        'name': 'Model D Minus',
        'brand': 'Glorious',
        'oldPrice': 60,
        'price': 59,
    },
    {
        'id':13,
        'img':'https://img.narong.dev/8KdQ27VZlVHLH9kTIUfsQe6O9WmfvgA7ZcZFqTbaNFM/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL2RfYmxhY2tfMGJiYTQyNjBiZC5wbmc.webp',
        'name': 'Model D Minus',
        'brand': 'Glorious',
        'oldPrice': 69,
        'price': 59,
    },
    {
        'id':14,
        'img':'https://img.narong.dev/rl7MQug3O2gvlh_dS2JzXbK5Q4XUNbqQk8rH1f-21Qk/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrL2Rfd2lyZWxlc3Nfd2hpdGVfOTAyYzhiOTM0YS5wbmc.webp',
        'name': 'Model D Wireless',
        'brand': 'Glorious',
        'oldPrice': 105,
        'price': 95,
    },
    {
        'id':15,
        'img':'https://img.narong.dev/Ywn__GJmUXJiQjKr5Inw2dcgoGKDVnKrQ7AFUx7ab30/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLzFfZDMxMWVlMjcwNS5wbmc.webp',
        'name': 'Lynx Standard (Lubed)',
        'brand': 'Glorious',
        'oldPrice': 49,
        'price': 45,
    },
    {
        'id':16,
        'img':'https://img.narong.dev/laaMqZFk59iMFdft4INBJ8TNxAp0BzGhcXwMhMr1q5w/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLzFfY2I4Y2Y1Yjk1Ni5wbmc.webp',
        'name': 'Lynx (UnLubed)',
        'brand': 'Glorious',
        'oldPrice': 35,
        'price': 29 ,
    },
    {
        'id':17,
        'img':'https://img.narong.dev/4Ci1J0-G_RmYZhldRf9oVGRNvt7oxaAs_xuHVSi4WJc/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLzFfMGVhZGRhYmNjYy5wbmc.webp',
        'name': 'Panada (UnLubed)',
        'brand': 'Glorious',
        'oldPrice': 35,
        'price': 29 ,
    },
    {
        'id':18,
        'img':'https://img.narong.dev/y7AVaurrpcWgFRnhezhKx6Hcyo3zSiuo_iho82r4Bck/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLzFfZDY3MWU1YjU0MC5wbmc.webp',
        'name': 'Panada (Lubed)',
        'brand': 'Glorious',
        'oldPrice': 49,
        'price': 45,
    },
    {
        'id':19,
        'img':'https://img.narong.dev/uiyozSO8RXFzd0032KAVgK1lng8iTdyG4IM_pTz-Cq4/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2dsb3Jpb3VzX2F1cmFfa2V5Y2Fwc192Ml9ibGFja184OGJhMTE1MjNmZmE5NzEzMTExN2JhOTM2YmZjMzY0OC5qcGc.webp',
        'name': 'Aura Keycaps V2',
        'brand': 'Glorious',
        'oldPrice': 45,
        'price': 39,
    },
    {
        'id':20,
        'img':'https://img.narong.dev/uXGNRXWSGiub8moYR8kc8L6Zhz5KhcGSg2XKTZUiSW8/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2dsb3Jpb3VzX2F1cmFfa2V5Y2Fwc192Ml93aGl0ZV83MDNmNTYzYzJlZTczOWU0MzU3OThhNzI0NjljNTU3ZS5qcGc.webp',
        'name': 'Aura Keycaps V2',
        'brand': 'Glorious',
        'oldPrice': 45,
        'price': 39,
    },
    {
        'id':21,
        'img':'https://img.narong.dev/DHbJxGxeE1tv0cqOnnmm1nBeiG_wAQM9mrQkL9BkF8Y/rs:fit:640:/aHR0cHM6Ly9hc3NldHMtY2RuLmphbWJ1bnRlY2guZGV2L3RrLWZpbGVzL2dsb3Jpb3VzX2F1cmFfa2V5Y2Fwc192Ml9waW5rXzVjZjM5YjkxYjY2NGRkM2U2N2JlMmUzNjAwNDc0NmZiLmpwZw.webp',
        'name': 'Aura Keycaps V2',
        'brand': 'Glorious',
        'oldPrice': 45,
        'price': 39,
    },
] 